# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2026 Project Tick
# SPDX-FileContributor: Project Tick

# Copyright (c) 2026 Project Tick

# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
# of the Software, and to permit persons to whom the Software is furnished to do
# so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

knpu_oauth2_client:
    clients:
        github:
            type: github
            client_id: '%env(OAUTH_GITHUB_ID)%'
            client_secret: '%env(OAUTH_GITHUB_SECRET)%'
            redirect_route: connect_github_check
            redirect_params: {}

        gitlab:
            type: generic
            provider_class: League\OAuth2\Client\Provider\GenericProvider
            client_id: '%env(OAUTH_GITLAB_ID)%'
            client_secret: '%env(OAUTH_GITLAB_SECRET)%'
            redirect_route: connect_gitlab_check
            provider_options:
                urlAuthorize: 'https://gitlab.com/oauth/authorize'
                urlAccessToken: 'https://gitlab.com/oauth/token'
                urlResourceOwnerDetails: 'https://gitlab.com/api/v4/user'

        microsoft:
            type: generic
            provider_class: League\OAuth2\Client\Provider\GenericProvider
            client_id: '%env(OAUTH_MICROSOFT_ID)%'
            client_secret: '%env(OAUTH_MICROSOFT_SECRET)%'
            redirect_route: connect_microsoft_check
            provider_options:
                urlAuthorize: 'https://login.microsoftonline.com/consumers/oauth2/v2.0/authorize'
                urlAccessToken: 'https://login.microsoftonline.com/consumers/oauth2/v2.0/token'
                urlResourceOwnerDetails: 'https://graph.microsoft.com/v1.0/me'
