#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "projecttickgitbundle"
name = "Project Tick Git Service Bundle"
description.en = "Project Tick Git System Bundle packages a customized version of git and gitolite developed by Project Tick."
description.fr = "Le pack Project Tick Git System Bundle contient une version personnalisée de git et gitolite développée par Project Tick."
description.tr = "Project Tick Git System Bundle, Project Tick tarafından geliştirilen özelleştirilmiş bir git ve gitolite sürümünü içerir."

version = "0.0.5-1~ynh1"

maintainers = ["Mehmet Samet Duman"]

[upstream]
license = "GPL-2.0-only, GPL-2.0-or-later"
website = "https://projecttick.org"
admindoc = "https://projecttick.org/handbook"
userdoc = "https://projecttick.org/handbook"
code = "https://git.projecttick.org"

[integration]
yunohost = ">= 12.1.17"
helpers_version = "2.1"
architectures = "amd64"
multi_instance = false

ldap = "not_relevant"

sso = "not_relevant"

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin_ssh_key]
    ask.en = "Admin SSH public key"
    ask.fr = "Clé publique SSH administrateur"
    ask.tr = "Yonetici SSH acik anahtari"
    help.en = "Paste a single-line SSH public key, e.g. ssh-ed25519 AAAA... user@host"
    help.fr = "Collez une clé publique SSH sur une seule ligne, ex: ssh-ed25519 AAAA... user@host"
    help.tr = "Tek satir SSH acik anahtari girin, ornek: ssh-ed25519 AAAA... user@host"
    type = "string"

[resources]

    [resources.sources]

    [resources.sources.cgit]
    url = "https://git.projecttick.org/pub/scm/Project-Tick-Infra/cgit.git/snapshot/cgit-0038bee93d00b87097d86fe172ff81a28a5799e9.tar.gz"
    sha256 = "58bacb5212e20b748d75db3c95a1d7ed117e718000112b51eb644e1888623c65"

    [resources.sources.gitolite]
    url = "https://github.com/sitaramc/gitolite/archive/refs/tags/v3.6.14.tar.gz"
    sha256 = "46cd120323bb45fae24e202eb90fdfc77b51bc7a8ed085b0fa6936c3594145ee"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.ports]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "git, openssh-server, build-essential, perl, libc6, liblua5.1-0, zlib1g, python3-docutils, python3-markdown, python3-pygments, fcgiwrap, cgit"
