name: contribs
on: [push, pull_request]
jobs:
  ci-cmake:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Ubuntu all contribs
            os: ubuntu-latest
            cmake-args: -DPTLIBZIPPY_BUILD_ADA=ON -DPTLIBZIPPY_BUILD_BLAST=ON -DPTLIBZIPPY_BUILD_IOSTREAM3=ON -DPTLIBZIPPY_BUILD_MINIZIP=ON -DPTLIBZIPPY_BUILD_PUFF=ON -DPTLIBZIPPY_WITH_INFBACK9=ON -DPTLIBZIPPY_WITH_CRC32VX=ON -DPTLIBZIPPY_WITH_GVMAT64=ON
            src_dir: .

          - name: Ubuntu ADA
            os: ubuntu-latest
            src_dir: contrib/ada
            install_ptlibzippy: yes

          - name: Ubuntu BLAST
            os: ubuntu-latest
            src_dir: contrib/blast
            install_ptlibzippy: yes

          - name: Ubuntu IOSTREAM
            os: ubuntu-latest
            src_dir: contrib/iostream3
            install_ptlibzippy: yes

          - name: Ubuntu MINIZIP
            os: ubuntu-latest
            src_dir: contrib/minizip
            install_ptlibzippy: yes

          - name: Ubuntu PUFF
            os: ubuntu-latest
            src_dir: contrib/puff
            install_ptlibzippy: yes

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install packages
      run: |
        sudo apt install gnat libbz2-dev

    - name: Install PTlibzippy
      if: ${{ matrix.install_ptlibzippy == 'yes' }}
      run: |
        cmake -S . -B ../build-ptlibzippy -DCMAKE_BUILD_TYPE=Release
        cmake --build ../build-ptlibzippy --config Release
        sudo cmake --install ../build-ptlibzippy

    - name: Generate project files
      run: cmake -S ${{ matrix.src_dir }} -B ../build ${{ matrix.cmake-args }} -DCMAKE_BUILD_TYPE=Release

    - name: Compile source code
      run: cmake --build ../build --config Release

    - name: Run test cases
      run: ctest -C Release --output-on-failure --max-width 120
      working-directory: ../build
